version: '3.8'
services:
  php-apache-environment:
    container_name: vanilla-way-php-apache
    build:
        context: ./php
        dockerfile: Dockerfile
    depends_on:
        - db
    volumes:
      - ./php/src:/var/www/html/
    ports:
      - 8080:80

  db:
    container_name: vanilla-way-db
    image: mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MY_DATABASE}
    ports:
        - "9906:3306"
  
  adminer:
    container_name: vanilla-way-adminer
    image: 'adminer:latest'
    ports:
        - "8081:8080"
    environment:
        ADMINER_DESIGN: dracula